lib/check_answers_web/router.ex
defmodule CheckAnswersWeb.Router do
  use CheckAnswersWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CheckAnswersWeb do
    pipe_through :browser

    get "/", TemplateValidatorController, :validate
    post "/", TemplateValidatorController, :submit
  end

  # Other scopes may use custom stacks.
  # scope "/api", CheckAnswersWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: CheckAnswersWeb.Telemetry
    end
  end
end

lib/check_answers/template_validator.ex
defmodule CheckAnswers.TemplateValidator do
  alias CheckAnswers.FilesParser

  @not_found_message "NÃO ENCONTRADA"

  def validate(answer_files, template_file, questions_to_validate) do
    answers = FilesParser.answers_from_html(answer_files)
    template_answers = FilesParser.answers_from_csv(template_file)

    compare_answers(answers, template_answers, questions_to_validate)
  end

  defp compare_answers(answers, template_answers, questions_to_validate) do
    Enum.map(questions_to_validate, fn question_number ->
      answer = find_answer(answers, question_number) |> String.upcase()
      template_answer = find_answer(template_answers, question_number) |> String.upcase()

      question_answers = %{
        question: question_number,
        correct_answer: answer,
        template_answer: template_answer
      }

      if same_answer?(answer, template_answer) do
        {:ok, question_answers}
      else
        {:error, question_answers}
      end
    end)
  end

  defp same_answer?(answer, template_answer) do
    answer == template_answer && template_answer != @not_found_message
  end

  defp find_answer(answers, question_number) do
    case Enum.find(answers, &(&1.question == question_number)) do
      %{answer: answer} -> answer
      _ -> @not_found_message
    end
  end
end

lib/check_answers_web/controllers/template_validator_controller.ex
defmodule CheckAnswersWeb.TemplateValidatorController do
  use CheckAnswersWeb, :controller
  require Logger

  alias CheckAnswers.TemplateValidator
  alias CheckAnswers.FilesHelper

  @questions_to_validate 6..180

  def validate(conn, _params) do
    render(conn, "validate.html", changeset: :check_answers)
  end

  def submit(conn, %{"answer_files" => answer_files, "template" => template_file}) do
    try do
      template_file_name = FilesHelper.upload_file(template_file.path, template_file.filename)
      answer_file_names = Enum.map(answer_files, &FilesHelper.upload_file(&1.path, &1.filename))

      validations =
        TemplateValidator.validate(
          answer_file_names,
          template_file_name,
          @questions_to_validate
        )

      FilesHelper.delete_files(answer_file_names ++ [template_file_name])
      handle_validations(conn, validations)
    rescue
      error ->
        handle_error(conn, error)
    end
  end

  defp handle_error(conn, error) do
    conn
    |> put_flash(:error, error.message)
    |> render("validate.html", changeset: :check_answers)
  end

  defp handle_validations(conn, validations) do
    invalid_answers =
      Enum.filter(validations, fn {validation, _} ->
        validation == :error
      end)

    if invalid_answers == [] do
      conn
      |> put_flash(:info, "Nenhuma Inconsistência!")
      |> render("result.html", results: invalid_answers)
    else
      render(conn, "result.html", results: invalid_answers)
    end
  end
end

lib/check_answers_web/views/template_validator_view.ex
defmodule CheckAnswersWeb.TemplateValidatorView do
  use CheckAnswersWeb, :view
end

lib/check_answers_web/templates/template_validator/form.html.eex
 <%= form_for @changeset, @action, [multipart: true], fn f -> %>
    <div class="form-group">
      <label>Validação das respostas das questões 6 a 180 do Simulado ENEM</label>
      <br>

      <label>Gabarito</label>
      <input type="file" id="template" name="template">
      
      <label>Arquivos de Respostas</label>
      <input type="file" id="answer_files" name="answer_files[]" multiple>
    </div>

    <div class="form-group">
      <%= submit "Validar", class: "btn btn-primary" %>
    </div>
  <% end %>

lib/check_answers_web/templates/template_validator/result.html.eex
<section class="column">
<h2>Inconsistências<h2>
<table>
    <thead>
      <tr>
        <th>Questão</th>
        <th>Resposta Correta</th>
        <th>Resposta do Gabarito</th>
      </tr>
    </thead>
    <tbody>
  <%= for {validation, question_answers} <- @results do %>
    <%= if validation == :error do %>
      <tr>
        <td><%= question_answers.question %></td>
        <td><%= question_answers.correct_answer %></td>
        <td><%= question_answers.template_answer %></td>
      </tr>
    <% end %>
  <% end %>
    </tbody>
  </table>

  <span><%= link "Voltar", to: Routes.template_validator_path(@conn, :validate) %></span>
</section>

lib/check_answers_web/templates/template_validator/validate.html.eex
<section class="phx-hero">
  <h1>Validador de Gabarito ENEM</h1>
</section>

<section class="row">
  <%= render "form.html", Map.put(assigns, :action, Routes.template_validator_path(@conn, :submit)) %>
</section>